### ISSUE TITLE
Align related events and map to the right

### ISSUE THREAD

**Issue by karllapuz** [HA-SJSU/hammer_theatre#15]
Align all in the same div

**Comment by ykrsm** [comment]
Bad
![screen shot 2018-05-23 at 10 00 41 am](https://user-images.githubusercontent.com/12422309/40439577-3292d2c8-5e70-11e8-8073-f2c260654965.png)

Good
![screen shot 2018-05-23 at 10 00 33 am](https://user-images.githubusercontent.com/12422309/40439581-35637e1c-5e70-11e8-8a6f-e3feeddd2c3e.png)

**Comment by SairenDelight** [comment]
![screen shot 2018-05-23 at 10 45 09 am](https://user-images.githubusercontent.com/22091894/40441619-6aeae326-5e76-11e8-8fcb-3c077806bfce.png)
Done waiting for review
