### ISSUE TITLE
Look back banner's background color not rendered when display width is 768 px

### ISSUE THREAD

**Issue by ykrsm** [HA-SJSU/hammer_theatre#18]
Bad
![screen shot 2018-05-14 at 11 07 56 am](https://user-images.githubusercontent.com/12422309/40015126-365d28c8-5767-11e8-9fdc-f0819965ebd2.png)

Good
![screen shot 2018-05-14 at 11 09 19 am](https://user-images.githubusercontent.com/12422309/40015152-4322db0c-5767-11e8-990c-29d7b4ed3271.png)

**Comment by SairenDelight** [comment]
For some reason it would turn back into 600px instead of staying in the 200px zone. The div id "home-quote-picture" is blocking the div id "home-lookback-banner-mobile" attributes due to its larger size. It also doesn't help that the div id "home-lookback-banner-mobile" has content as 0px.

**Comment by SairenDelight** [comment]
![screen shot 2018-06-21 at 10 25 12 am](https://user-images.githubusercontent.com/22091894/41735238-01ff9dfa-753e-11e8-8cda-5a347ffebbb6.png)

**Comment by manpreetsjsu** [comment]
Vivian worked on this issue and fixed the bug... hence closing the issue
