### ISSUE TITLE
Fix alignment issue with input elements for contact page

### ISSUE THREAD

**Issue by ykrsm** [HA-SJSU/hammer_theatre#32]

**Comment by ykrsm** [comment]
![screen shot 2018-05-23 at 10 58 31 am](https://user-images.githubusercontent.com/12422309/40442353-400bf666-5e78-11e8-87ac-3dec89cbb48b.png)

**Comment by SairenDelight** [comment]
![screen shot 2018-05-23 at 11 15 08 am](https://user-images.githubusercontent.com/22091894/40443278-af71c9d4-5e7a-11e8-86bb-c7dde85bf514.png)
Input form aligns when less than 600 px
