### ISSUE TITLE
Bug Rental page input alignment

### ISSUE THREAD

**Issue by ykrsm** [HA-SJSU/hammer_theatre#33]

**Comment by ykrsm** [comment]
![screen shot 2018-05-23 at 11 23 15 am](https://user-images.githubusercontent.com/12422309/40443621-c05f85dc-5e7b-11e8-9e1c-c3272b871ba6.png)

**Comment by SairenDelight** [comment]
![screen shot 2018-05-23 at 11 28 34 am](https://user-images.githubusercontent.com/22091894/40443918-a21d6e9e-5e7c-11e8-84fe-7519f20b4890.png)
Fixed the input alignments for anything less than 600 px
