### ISSUE TITLE
Create "Archives" page

### ISSUE THREAD

**Issue by karllapuz** [HA-SJSU/hammer_theatre#40]
Figure out how Wordpress is implemented by previous web team and add a new page called Archives which automatically stores an event after it is done

**Comment by manpreetsjsu** [comment]
i have locally installed the wordpress and i am trying to figure out the work flow of the wordpress.....

**Comment by manpreetsjsu** [comment]
created archived events page.... you can have look in the staging site and the link is also attached in the navigation bar as "ARCHIVED EVENTS" in the hamburger/sandwich..............

**Comment by karllapuz** [comment]
Wait for graphic design team to send "Archives" banner

**Comment by karllapuz** [comment]
Optimize images for smaller screens (make them go smaller as screen size gets smaller)

**Comment by manpreetsjsu** [comment]
archived page is created and live ..... just need littile fixes ... closing the issue
