### ISSUE TITLE
Wikipedia page

### ISSUE THREAD

**Issue by ykrsm** [HA-SJSU/hammer_theatre#6]
Re-submit Hammer Theatre Wikipedia page.
Get the new copy from Editorial.

**Comment by ykrsm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wikipedia](https://trello.com/c/XPxZD7FJ/1-wikipedia)

**Comment by karllapuz** [comment]
Awaiting review results from Wikipedia team

**Comment by karllapuz** [comment]
Flesh out and add change subject from "Hammer Theatre" to "Hammer Theatre Center"

**Comment by ykrsm** [comment]
Discuss with Sheryl about adding more content after finals
